modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Microcontrollers"
description = "${description}"
logoFile = "assets/${id}/icon.png"

[["dependencies.${id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${forgeConstraint}"
ordering = "NONE"
side = "CLIENT"

[["dependencies.${id}"]]
modId = "minecraft"
type = "required"
versionRange = "${mcdep}"
ordering = "NONE"
side = "CLIENT"

[["dependencies.${id}"]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[${yacl_version},)"
ordering = "BEFORE"
side = "CLIENT"

[[mixins]]
config = "${id}.mixins.json"
